config/routes.rb
Rails.application.routes.draw do
  # api----------------------
  namespace :api do
    namespace :v1 do
      resources :microposts, only: %i[create destroy index] do
        resources :likes, only: %i[create destroy]
      end
      get :static_pages, to: "static_pages#home"
      # Header
      get "/create_micropost", to: "static_pages#create_micropost"
      # Footer
      get "/ranking", to: "static_pages#ranking"
      get "/search", to: "microposts#search"
      resources :users
      # Others
      get "password_resets/new"
      get "password_resets/edit"
      resources :microposts, only: %i[create destroy index] do
        resources :likes, only: %i[create destroy]
      end
      resources :account_activations, only: [:edit]
        resources :password_resets, only: %i[new create edit update]
          get "/signup", to: "users#new"
          post "/login", to: "sessions#create"
          delete "/logout", to: "sessions#destroy"
          post "/guest", to: "guest_sessions#create"
        end
      end
  # api----------------------
  root "static_pages#home"
  # Header
  get "/create_micropost", to: "static_pages#create_micropost"
  # Footer
  get "/ranking", to: "static_pages#ranking"
  get "/search", to: "microposts#search"
  resources :users
  # Others
  get "password_resets/new"
  get "password_resets/edit"
  resources :microposts, only: %i[create destroy index] do
    resources :likes, only: %i[create destroy]
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  get "/signup", to: "users#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  post "/guest", to: "guest_sessions#create"
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token

  has_many :microposts, dependent: :destroy # userが消えるとmicropostも消える
  before_save   :downcase_email
  before_create :create_activation_digest
  # before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  # validates :email, presence: true, length: { maximum: 255 },
  #                   format: { with: Settings.valid_email_regex },
  #                   uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :micropost
  # 渡された文字列のハッシュ値を返す
  def self.digest(string)
    cost = if ActiveModel::SecurePassword.min_cost
             BCrypt::Engine::MIN_COST
           else
             BCrypt::Engine.cost
           end
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # トークンがダイジェストと一致したらtrueを返す
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?

    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  # アカウントを有効にする
  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  # 有効化用のメールを送信する
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # パスワード再設定の属性を設定する
  def create_reset_digest
    self.reset_token = User.new_token
    # update_attribute(:reset_digest,  User.digest(reset_token))
    # update_attribute(:reset_sent_at, Time.zone.now)
    update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)
  end

  # パスワード再設定のメールを送信する
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # パスワード再設定の期限が切れている場合はtrueを返す
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  # 試作feedの定義
  # 完全な実装は次章の「ユーザーをフォローする」を参照
  # ユーザーのステータスフィードを返す
  def feed
    Micropost
  end

  def already_liked?(micropost)
    self.likes.exists?(micropost_id: micropost.id)
  end

  private

  # メールアドレスをすべて小文字にする
  def downcase_email
    self.email = email.downcase
  end

  # 有効化トークンとダイジェストを作成および代入する
  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: %i[index edit update destroy]
  before_action :correct_user, only: %i[edit update]
  before_action :admin_user, only: :destroy
  # GET /users
  # GET /users.json
  def index
    @users = User.where(activated: true).paginate(page: params[:page])
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    if @user.guest && !current_user.guest
      flash[:warning] = 'アクセスできないページです'
      redirect_to root_path
    end
    redirect_to root_url and return unless @user.activated?

    @microposts = @user.microposts.paginate(page: params[:page], per_page: 10)
  end

  # GET /users/new
  def new
    @user = User.new
    redirect_to root_path if logged_in?
  end

  # GET /users/1/edit
  def edit
    if logged_in?
      @user = User.find(params[:id])
    else
      flash[:info] = 'アカウントを有効にするには、メールをご確認ください'
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      redirect_to signup_path
      flash[:info] = 'アカウントを有効にするには、メールをご確認ください'
    else
      redirect_to signup_path
      flash[:danger] = '無効な情報です'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update(user_params)
        flash[:success] = 'プロフィールを更新しました'
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = 'ユーザーを削除しました'
    redirect_to users_url
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # 渡されたユーザーのGravatar画像を返す
  def gravatar_for(user, options = { size: 80 })
    size         = options[:size]
    gravatar_id  = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :name %>
<%= f.text_field :name, class: 'form-control' %>

<%= f.label :email %>
<%= f.email_field :email, class: 'form-control' %>

<%= f.label :password %>
<%= f.password_field :password, class: 'form-control' %>

<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation, class: 'form-control' %>

<%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_guest_login.erb
<%= link_to 'ゲストユーザーでログイン', guest_path, method: :post, class: 'btn' %>

app/views/users/_new_login.html.erb
<div class="container">
    <h1>ログイン</h1>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <%= form_with(url: login_path, scope: :session, local: true) do |f| %>
            <%= f.label "メールアドレス" %>
            <%= f.email_field :email, class: 'form-control' %>
            <%= f.label "パスワード" %>
            <%= link_to "(パスワードをお忘れですか?)", new_password_reset_path %>
            <%= f.password_field :password, class: 'form-control' %>
            <%= f.label :remember_me, class: "checkbox inline" do %>
            <%= f.check_box :remember_me %>
            <span>記憶させますか？</span>
            <% end %>
            <%= f.submit "ログイン", class: "btn" %>
            <% end %>
        </div>
    </div>
</div>

app/views/users/_new_signup.html.erb
<div class="container">
    <h1>サインアップ</h1>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <%= form_with(model: @user, local: true) do |f| %>
            <%= f.label "ニックネーム" %>
            <%= f.text_field :name, class: 'form-control' %>

            <%= f.label "メールアドレス" %>
            <%= f.email_field :email, class: 'form-control' %>

            <%= f.label "パスワード" %>
            <%= f.password_field :password, class: 'form-control' %>

            <%= f.label "パスワードの確認" %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>

            <%= f.submit "登録", class: "btn" %>
            <% end %>
        </div>
    </div>
</div>

app/views/users/_show_else.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
      <% if current_user?(@user) %>
        <%= link_to edit_user_path do %>
          <h2>
          編集
          </h2>
        <% end %>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @user.microposts.any? %>
    <h3>Microposts (<%= @user.microposts.count %>)</h3>
    <ol class="microposts">
      <%= render @microposts %>
    </ol>
    <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>

app/views/users/_show_if.erb
<section class="login">
<h2>ゲストログイン中です</h2>
<h2>登録してください</h2>
<div class="login-form">
  <div class="tab-wrap">
    <input id="TAB-01" type="radio" name="TAB" class="tab-switch" checked="checked" />
    <label class="tab-label" for="TAB-01">Log in</label>
    <div class="tab-content">
      <%= render "new_login" %>
    </div>
    <input id="TAB-02" type="radio" name="TAB" class="tab-switch" />
    <label class="tab-label" for="TAB-02">Sign up</label>
    <div class="tab-content">
      <%= render "new_signup" %>
    </div>
  </div>
</div>
</section>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'プロフィールの更新') %>
<% provide(:button_text, '変更を保存する') %>
<h1>プロフィールの更新</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="https://gravatar.com/emails" target="_blank" rel="noopener">更新</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>全てのユーザー</h1>
<%= will_paginate %>
<ul class="users">
  <%= render @users%>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<body>
  <section class="login">
    <div>
      <ul>
        <li class="app-visual-login">
          <div>
            <h3>動画ネタの掲示板 <span class="brand-name">YouIdea</span></h3>
            <%= image_tag "signup" ,class: "signup" %>
            <h3>あなたの動画ネタをクリエイターに届けよう</h3>
            <h3>リスナーとの新たな繋がり <span class="brand-name">YouIdea</span></h3>
          </div>
        </li>
        <li class="login-form">
          <div class="wrapper">
            <h1 class="brand-name">YouIdea</h1>
            <%flash.each do |message_type,message|%>
            <%= content_tag(:div,message,class: "alert alert-#{message_type}")%>
            <%end%>
            <div class="tab-wrap">
              <input id="TAB-01" type="radio" name="TAB" class="tab-switch" checked="checked" />
              <label class="tab-label" for="TAB-01">Log in</label>
              <div class="tab-content">
                <%= render  "new_login" %>
              </div>
              <input id="TAB-02" type="radio" name="TAB" class="tab-switch" />
              <label class="tab-label" for="TAB-02">Sign up</label>
              <div class="tab-content">
                <%= render  "new_signup" %>
              </div>
            </div>
            <div class="guest_login">
            <%= render  "guest_login" %>
            </div>
          </div>
        </li>
      </ul>
    </div>
  </section>
</body>

app/views/users/show.html.erb
<% if @user.guest && current_user.guest %>
<%= render "show_if" %>
<% else %>
<%= render "show_else" %>
<% end %>
<% if current_user?(@user) %>
<div class="profile-logout">
  <%= link_to logout_path,class:"btn", method: :delete do %>
    <% if current_user.guest%>
    <p>トップページへ</p>
    <% else %>
    <p>ログアウト</p>
    <% end %>
  <% end %>
  </div>
<% end %>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
    </section>
    <section class="stats">
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>