config/routes.rb
Rails.application.routes.draw do
  # api----------------------
  namespace :api do
    namespace :v1 do
      resources :microposts, only: %i[create destroy index] do
        resources :likes, only: %i[create destroy]
      end
      get :static_pages, to: "static_pages#home"
      # Header
      get "/create_micropost", to: "static_pages#create_micropost"
      # Footer
      get "/ranking", to: "static_pages#ranking"
      get "/search", to: "microposts#search"
      resources :users
      # Others
      get "password_resets/new"
      get "password_resets/edit"
      resources :microposts, only: %i[create destroy index] do
        resources :likes, only: %i[create destroy]
      end
      resources :account_activations, only: [:edit]
        resources :password_resets, only: %i[new create edit update]
          get "/signup", to: "users#new"
          post "/login", to: "sessions#create"
          delete "/logout", to: "sessions#destroy"
          post "/guest", to: "guest_sessions#create"
        end
      end
  # api----------------------
  root "static_pages#home"
  # Header
  get "/create_micropost", to: "static_pages#create_micropost"
  # Footer
  get "/ranking", to: "static_pages#ranking"
  get "/search", to: "microposts#search"
  resources :users
  # Others
  get "password_resets/new"
  get "password_resets/edit"
  resources :microposts, only: %i[create destroy index] do
    resources :likes, only: %i[create destroy]
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  get "/signup", to: "users#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  post "/guest", to: "guest_sessions#create"
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
  has_one_attached :image
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 28 }
  validates :content, presence: true, length: { maximum: 140 }
  validates :image, content_type: { in: %w[image/jpeg image/gif image/png],
                                    message: 'must be a valid image format' },
                    size: { less_than: 5.megabytes,
                            message: 'should be less than 5MB' }
  # 表示用のリサイズ済み画像を返す
  def display_image
    image.variant(resize_to_limit: [500, 500])
  end

  def self.search(search)
    if search
      Micropost.where(['title LIKE ? OR content LIKE ? OR creater LIKE ?',
                       "%#{search}%", "%#{search}%", "%#{search}%"])
    end
  end
end

app/controllers/api/v1/microposts_controller.rb
module Api
  module V1
    class MicropostsController < ApplicationController
      before_action :logged_in_user, only: %i[destroy create]
            before_action :correct_user, only: :destroy

            def create
                @micropost = current_user.microposts.build(micropost_params)
                @micropost.image.attach(params[:micropost][:image])
                if @micropost.save
                    flash[:success] = '投稿が完了しました'
                    redirect_to root_path
                else
                    @feed_items = current_user.feed.paginate(page: params[:page])
                    render 'static_pages/create_micropost'
                end
            end

            def destroy
                @micropost.destroy
                flash[:success] = '投稿が削除されました'
                redirect_to request.referer || root_url
            end

            def search
                @feed_items = Micropost.search(params[:search]) if params[:search].present?
            end

            private

            def micropost_params
                params.require(:micropost).permit(:title, :content, :image, :creater)
            end

            def correct_user
                @micropost = current_user.microposts.find_by(id: params[:id])
                redirect_to root_url if @micropost.nil?
            end
    end
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: %i[destroy create]
  before_action :correct_user, only: :destroy

  def create
    @micropost = current_user.microposts.build(micropost_params)
    @micropost.image.attach(params[:micropost][:image])
    if @micropost.save
      flash[:success] = '投稿が完了しました'
      redirect_to root_path
    else
      @feed_items = current_user.feed.paginate(page: params[:page])
      render 'static_pages/create_micropost'
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = '投稿が削除されました'
    redirect_to request.referer || root_url
  end

  def search
    @feed_items = Micropost.search(params[:search]) if params[:search].present?
  end

  private

  def micropost_params
    params.require(:micropost).permit(:title, :content, :image, :creater)
  end

  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    redirect_to root_url if @micropost.nil?
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<div class="idea">
  <h3 class="title"><%= micropost.title %></h3>
  <ul class="user">
    <li class="left">
      <div class="user-icon">
        <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
      </div>
      <div class="user-name"><%= link_to micropost.user.name, micropost.user %></div>
      <div class="timestamp">
        <%= time_ago_in_words(micropost.created_at) %>前
      </div>
    </li>
    <li class="right">
      <%if current_user.email == micropost.user.email %>
      <%= button_to micropost_path(micropost), method: :delete do %>
      <i class="far fa-trash-alt"></i><br/>削除
      <% end %>
      <% end %>
    </li>
  </ul>
  <div class="detail">
    <%= micropost.content %>
  </div>
  <% if micropost.creater %>
  <ul class="creater">
    <li class="left">
      やって欲しいクリエイター
    </li>
    <li class="right">
      <%= micropost.creater %>
    </li>
  </ul>
  <% end %>
  <% if micropost.image.attached? %>
  <div class="thumbnail">
    <%= image_tag micropost.display_image %>
  </div>
  <% end %>
  <div class="judge">
    <h3>
      <% if current_user.already_liked?(micropost) %>
      <%= button_to micropost_like_path(micropost, id: current_user.id), method: :delete do %>
      <span class="heart-liked btn-icon">
        <i class="fas fa-heart"></i>
      </span>
      <% end %>
      <% else %>
      <%= button_to micropost_likes_path(micropost) do %>
      <span class="heart-not-liked btn-icon">
        <i class="far fa-heart"></i>
      </span>
      <% end %>
      <% end %>
      <%= micropost.likes.count %>
    </h3>
  </div>
</div>

app/views/microposts/search.html.erb
<section id="search">
    <h2>検索</h2>
    <%= form_tag(search_path, class: "search_container",:method => "get") do %>
    <%= text_field_tag :search %>
    <%= button_tag type:"submit",class: "submit", :name => nil do%>
    <i class="fas fa-search"></i>
    <% end %>
    <% end %>
    <% if !@feed_items.nil? %>
    <%= render @feed_items %>
    <% end %>
</section>