config/routes.rb
Rails.application.routes.draw do
  # api----------------------
  namespace :api do
    namespace :v1 do
      resources :microposts, only: %i[create destroy index] do
        resources :likes, only: %i[create destroy]
      end
      get :static_pages, to: "static_pages#home"
      # Header
      get "/create_micropost", to: "static_pages#create_micropost"
      # Footer
      get "/ranking", to: "static_pages#ranking"
      get "/search", to: "microposts#search"
      resources :users
      # Others
      get "password_resets/new"
      get "password_resets/edit"
      resources :microposts, only: %i[create destroy index] do
        resources :likes, only: %i[create destroy]
      end
      resources :account_activations, only: [:edit]
        resources :password_resets, only: %i[new create edit update]
          get "/signup", to: "users#new"
          post "/login", to: "sessions#create"
          delete "/logout", to: "sessions#destroy"
          post "/guest", to: "guest_sessions#create"
        end
      end
  # api----------------------
  root "static_pages#home"
  # Header
  get "/create_micropost", to: "static_pages#create_micropost"
  # Footer
  get "/ranking", to: "static_pages#ranking"
  get "/search", to: "microposts#search"
  resources :users
  # Others
  get "password_resets/new"
  get "password_resets/edit"
  resources :microposts, only: %i[create destroy index] do
    resources :likes, only: %i[create destroy]
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  get "/signup", to: "users#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  post "/guest", to: "guest_sessions#create"
end

app/views/layouts/_footer.html.erb
<footer>
  <div>
    <ul>
      <li>
        <%= link_to root_path do %>
        <i class="fas fa-home"></i>
        <% end %>
      </li>
      <li>
        <%= link_to ranking_path do %>
        <i class="fas fa-crown"></i>
        <% end %>
      </li>
      <li>
        <%= link_to search_path do%>
        <i class="fas fa-search"></i>
        <% end %>
      </li>
      <li>
        <%= link_to current_user do %>
        <i class="far fa-user"></i>
        <% end %>
      </li>
    </ul>
  </div>
</footer>

app/views/layouts/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
<%
=begin%>
  ここから
<%
=end%>
  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>
<%
=begin%>
  ここまで
<%
=end%>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/layouts/_head.html.erb
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= favicon_link_tag('favicon.ico') %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= render 'layouts/shim'%>
</head>

app/views/layouts/_header.html.erb
  <header>
    <div id="header-container">
      <%= link_to root_path do %>
        <%= embedded_svg "icon.svg" %>
      <% end %>
      <div id="header-right">
        <%= link_to create_micropost_path do %>
        <i class="fas fa-edit"></i>
        <% end %>
      </div>
    </div>
  </header>

app/views/layouts/application.html.erb
  <!DOCTYPE html>
  <html>
    <%= render "layouts/head"%>
    <% if logged_in? %>
      <body>
        <%= render 'layouts/header'%>
        <main>
          <div class="container">
          <%flash.each do |message_type,message|%>
            <%= content_tag(:div,message,class: "alert alert-#{message_type}")%>
          <%end%>
            <%= yield %>
          </div>
        </main>
        <%= debug(params) if Rails.env.development? %>
        <%= render "layouts/footer"%>
      </body>
    <% else %>
      <%= yield %>
<% end %>
  </html>

app/views/layouts/error_layout.erb
<!DOCTYPE html>
<html>
<%= render "layouts/head" %>
<body>
<%= render "layouts/header" %>
<main>
    <div class="container">
        <%= yield %>
    </div>
</main>
<%= debug(params) if Rails.env.development? %>
<%= render "layouts/footer" %>
</body>
</html>